import "bootstrap/dist/css/bootstrap.min.css";
import "../../public/assets/css/main.css";
import "react-perfect-scrollbar/dist/css/styles.css";
import "react-responsive-modal/styles.css";
import "swiper/css";
import "swiper/css/navigation";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./providers";
import ToastProvider from "@/components/core/ToasterProvider";

export const metadata = {
  title: "Glen Echo Nurseries",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
            rel="stylesheet"
            href="/css/main.css"
        />
    </head>
      <body>
        <Providers>
          <ToastProvider />
          {children}
        </Providers>
      </body>
    </html>
  );
}
